const mentors=[
{id:"maya-johnson",name:"Maya Johnson",initials:"MJ",sport:"Basketball",role:"College athlete",focus:["Confidence","Recruiting","School balance"],formats:["Virtual","In person"],color:"#2f7865",number:"24",location:"Atlanta, GA",availability:"2 spots",experience:"4 years",bio:"Maya helps young players build confidence, understand the college recruiting process, and create routines that make room for both school and sport."},
{id:"marcus-reed",name:"Marcus Reed",initials:"MR",sport:"Soccer",role:"Academy coach",focus:["Training","Leadership","Confidence"],formats:["Virtual"],color:"#d75d38",number:"10",location:"Chicago, IL",availability:"3 spots",experience:"8 years",bio:"Marcus is an academy coach who believes great players learn to communicate, recover from mistakes, and lead with consistency."},
{id:"nia-thompson",name:"Nia Thompson",initials:"NT",sport:"Track & Field",role:"Former D1 sprinter",focus:["College transition","Training","School balance"],formats:["Virtual","In person"],color:"#8264a8",number:"08",location:"Austin, TX",availability:"1 spot",experience:"5 years",bio:"Nia supports runners navigating training pressure, college transitions, and the mental side of competing at their best."},
{id:"alex-kim",name:"Alex Kim",initials:"AK",sport:"Tennis",role:"Youth performance coach",focus:["Confidence","Training"],formats:["Virtual","In person"],color:"#34788b",number:"07",location:"Seattle, WA",availability:"2 spots",experience:"6 years",bio:"Alex works with developing tennis players on match confidence, smart practice, and staying composed in high-pressure moments."},
{id:"elena-ruiz",name:"Elena Ruiz",initials:"ER",sport:"Volleyball",role:"College team captain",focus:["Leadership","Recruiting","School balance"],formats:["Virtual"],color:"#bb593c",number:"12",location:"San Diego, CA",availability:"4 spots",experience:"3 years",bio:"Elena shares practical guidance on recruiting, team leadership, and finding your voice in a competitive environment."},
{id:"jordan-brooks",name:"Jordan Brooks",initials:"JB",sport:"Swimming",role:"Former national competitor",focus:["Training","Confidence","School balance"],formats:["Virtual"],color:"#286d80",number:"16",location:"Baltimore, MD",availability:"2 spots",experience:"7 years",bio:"Jordan helps swimmers build sustainable habits, handle performance anxiety, and balance long training weeks with life outside the pool."},
{id:"sam-patel",name:"Sam Patel",initials:"SP",sport:"Basketball",role:"Skills trainer",focus:["Training","Recruiting"],formats:["In person"],color:"#6c7851",number:"31",location:"New York, NY",availability:"1 spot",experience:"9 years",bio:"Sam combines skills development with honest recruiting advice so athletes can focus their energy and present their game clearly."},
{id:"taylor-williams",name:"Taylor Williams",initials:"TW",sport:"Soccer",role:"Former college goalkeeper",focus:["College transition","Confidence","Leadership"],formats:["Virtual","In person"],color:"#84604f",number:"01",location:"Raleigh, NC",availability:"3 spots",experience:"4 years",bio:"Taylor mentors athletes through setbacks, big transitions, and the challenge of being a calm, vocal leader on the field."}
];
const state={requests:[],filters:{search:"",sport:"",focus:"",formats:[]}};
const growthData={
height:{values:[62,64,66,68,69],label:"Current height",value:"5 ft 9 in",change:"↑ 7 in across this preview",title:"Height history preview"},
weight:{values:[108,116,126,137,145],label:"Current weight",value:"145 lb",change:"↑ 37 lb across this preview",title:"Weight history preview"},
age:{values:[13,14,15,16,17],label:"Current age",value:"17 years",change:"5 annual check-ins in this preview",title:"Age history preview"}
};
let watchConnected=false;
const pages=[...document.querySelectorAll("[data-page]")];
const profileModal=document.querySelector("#profile-modal"),requestModal=document.querySelector("#request-modal"),reportModal=document.querySelector("#report-modal"),mobileNav=document.querySelector(".mobile-nav");
function mentorCard(m){return `<article class="mentor-card"><div class="mentor-art" style="background:${m.color}"><span class="mentor-status">✓ Sample mentor</span><span class="avatar-monogram">${m.initials}</span><span class="mentor-number">${m.number}</span></div><div class="mentor-card-body"><div class="mentor-meta"><span>${m.sport}</span><span>● ${m.availability}</span></div><h3>${m.name}</h3><p class="mentor-role">${m.role} · ${m.location}</p><div class="tag-list">${m.focus.slice(0,3).map(t=>`<span class="tag">${t}</span>`).join("")}</div><div class="mentor-card-actions"><button type="button" data-mentor-id="${m.id}">View profile</button><button type="button" data-request-id="${m.id}">Request intro</button></div></div></article>`}
function renderMentors(){document.querySelector("#featured-mentors").innerHTML=mentors.slice(0,3).map(mentorCard).join("");renderDirectory()}
function renderDirectory(){const term=state.filters.search.toLowerCase();let filtered=mentors.filter(m=>{const searchable=[m.name,m.sport,m.role,...m.focus].join(" ").toLowerCase();return(!term||searchable.includes(term))&&(!state.filters.sport||m.sport===state.filters.sport)&&(!state.filters.focus||m.focus.includes(state.filters.focus))&&(!state.filters.formats.length||state.filters.formats.some(f=>m.formats.includes(f)))});const sort=document.querySelector("#sort-filter").value;if(sort==="name")filtered.sort((a,b)=>a.name.localeCompare(b.name));if(sort==="sport")filtered.sort((a,b)=>a.sport.localeCompare(b.sport));document.querySelector("#mentor-directory").innerHTML=filtered.map(mentorCard).join("");document.querySelector("#mentor-count").textContent=`${filtered.length} mentor${filtered.length===1?"":"s"}`;document.querySelector("#mentor-empty").classList.toggle("show",!filtered.length)}
function clearFilters(){state.filters={search:"",sport:"",focus:"",formats:[]};["#mentor-search","#sport-filter","#focus-filter"].forEach(s=>document.querySelector(s).value="");document.querySelectorAll('input[name="format"]').forEach(i=>i.checked=false);renderDirectory()}
function goToPage(name,updateHash=true){const dest=pages.some(p=>p.dataset.page===name)?name:"home";pages.forEach(p=>p.classList.toggle("active",p.dataset.page===dest));mobileNav.classList.remove("open");document.querySelector(".menu-button").setAttribute("aria-expanded","false");document.querySelector(".account-menu")?.removeAttribute("open");if(updateHash)history.replaceState(null,"",`#${dest}`);window.scrollTo({top:0,behavior:"smooth"});if(dest==="dashboard")renderRequests();if(dest==="athlete-profile")renderGrowthChart(document.querySelector("[data-growth-metric].active")?.dataset.growthMetric||"height")}
function findMentor(id){return mentors.find(m=>m.id===id)}
function openModal(modal){modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");setTimeout(()=>modal.querySelector("button,input,select")?.focus(),30)}
function closeModal(modal){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");if(!document.querySelector(".modal-backdrop.open"))document.body.classList.remove("modal-open")}
function openProfile(id){const m=findMentor(id);if(!m)return;document.querySelector("#profile-content").innerHTML=`<div class="profile-header" style="background:${m.color}"><div class="profile-header-content"><span class="verified-badge">✓ Sample profile</span><h2 id="profile-name">${m.name}</h2><p>${m.sport} · ${m.role}</p></div></div><div class="profile-body"><h3>How ${m.name.split(" ")[0]} can help</h3><p>${m.bio}</p><div class="tag-list">${m.focus.map(t=>`<span class="tag">${t}</span>`).join("")}</div><div class="profile-details"><div><span>Location</span><strong>${m.location}</strong></div><div><span>Format</span><strong>${m.formats.join(" / ")}</strong></div><div><span>Mentoring</span><strong>${m.experience}</strong></div></div><button class="button button-primary full-button" type="button" data-request-id="${m.id}">Request an introduction <span>→</span></button></div>`;openModal(profileModal)}
function openRequest(id){const m=findMentor(id);if(!m)return;closeModal(profileModal);document.querySelector("#request-mentor-id").value=m.id;document.querySelector("#selected-mentor").innerHTML=`<div class="mini-avatar" style="background:${m.color}">${m.initials}</div><p><strong>${m.name}</strong>${m.sport} · ${m.role}</p>`;openModal(requestModal)}
function showToast(title,message){const toast=document.querySelector("#toast");document.querySelector("#toast-title").textContent=title;document.querySelector("#toast-message").textContent=message;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),4200)}
function renderRequests(){const list=document.querySelector("#request-list"),empty=document.querySelector("#dashboard-empty");document.querySelector("#pending-count").textContent=state.requests.length;empty.classList.toggle("show",!state.requests.length);list.innerHTML=state.requests.map(r=>{const m=findMentor(r.mentorId);return `<div class="request-item"><div class="request-person"><div class="mini-avatar" style="background:${m.color}">${m.initials}</div><div><h3>${m.name}</h3><p>${r.goal} · Submitted this session</p></div></div><span class="pending-chip">Pending</span></div>`}).join("")}
function renderGrowthChart(metric){
  const data=growthData[metric]||growthData.height,line=document.querySelector("#growth-line"),pointsGroup=document.querySelector("#growth-points");
  if(!line||!pointsGroup)return;
  const min=Math.min(...data.values),max=Math.max(...data.values),range=max-min||1;
  const points=data.values.map((value,index)=>({x:48+index*(542/(data.values.length-1)),y:176-((value-min)/range)*141}));
  line.setAttribute("points",points.map(point=>point.x+","+point.y).join(" "));
  pointsGroup.replaceChildren(...points.map(point=>{const circle=document.createElementNS("http://www.w3.org/2000/svg","circle");circle.setAttribute("cx",point.x);circle.setAttribute("cy",point.y);circle.setAttribute("r","6");return circle}));
  document.querySelector("#growth-label").textContent=data.label;
  document.querySelector("#growth-value").textContent=data.value;
  document.querySelector("#growth-change").textContent=data.change;
  document.querySelector("#growth-chart-title").textContent=data.title;
  document.querySelectorAll("[data-growth-metric]").forEach(button=>{const active=button.dataset.growthMetric===metric;button.classList.toggle("active",active);button.setAttribute("aria-selected",String(active))});
}
function toggleWatch(){
  watchConnected=!watchConnected;
  const status=document.querySelector("#watch-status"),button=document.querySelector("#watch-connect");
  status.classList.toggle("connected",watchConnected);
  status.innerHTML=watchConnected?"<i></i> Demo connected":"<i></i> Not connected";
  document.querySelector("#watch-face").textContent=watchConnected?"72":"--";
  document.querySelector("#watch-steps").textContent=watchConnected?"8,462":"—";
  document.querySelector("#watch-minutes").textContent=watchConnected?"68 min":"—";
  document.querySelector("#watch-heart").textContent=watchConnected?"58 bpm":"—";
  document.querySelector("#watch-sleep").textContent=watchConnected?"7h 42m":"—";
  button.innerHTML=watchConnected?"Disconnect demo <span>×</span>":"Connect smartwatch <span>＋</span>";
  showToast(watchConnected?"Demo watch connected":"Demo watch disconnected",watchConnected?"Sample health metrics are now visible. No device was accessed.":"The sample health metrics were cleared.");
}
document.addEventListener("click",e=>{const route=e.target.closest("[data-route]");if(route){e.preventDefault();goToPage(route.dataset.route);return}const scroll=e.target.closest("[data-scroll]");if(scroll){e.preventDefault();goToPage("home");setTimeout(()=>document.querySelector(`#${scroll.dataset.scroll}`)?.scrollIntoView({behavior:"smooth"}),120);return}const profile=e.target.closest("[data-mentor-id]");if(profile){openProfile(profile.dataset.mentorId);return}const request=e.target.closest("[data-request-id]");if(request){openRequest(request.dataset.requestId);return}const sport=e.target.closest("[data-sport-jump]");if(sport){goToPage("discover");state.filters.sport=sport.dataset.sportJump;document.querySelector("#sport-filter").value=state.filters.sport;renderDirectory();return}if(e.target.closest("[data-report-open]")){openModal(reportModal);return}const closer=e.target.closest("[data-modal-close]");if(closer){closeModal(closer.closest(".modal-backdrop"));return}if(e.target.classList.contains("modal-backdrop"))closeModal(e.target);if(e.target.closest("[data-coming-soon]"))showToast("Coming next","This area is ready for a future database connection.")});
document.addEventListener("click",e=>{const metric=e.target.closest("[data-growth-metric]");if(metric){renderGrowthChart(metric.dataset.growthMetric);return}if(e.target.closest("[data-watch-connect]")){toggleWatch();return}if(e.target.closest("[data-profile-action]"))showToast("Ready for the database","Editing and saved activity will be enabled when accounts and storage are connected.");const privacy=e.target.closest("#privacy-toggle");if(privacy){const isPublic=privacy.getAttribute("aria-pressed")!=="true";privacy.setAttribute("aria-pressed",String(isPublic));privacy.textContent=isPublic?"Make private":"Make public";const label=document.querySelector("#profile-visibility");label.classList.toggle("public",isPublic);label.innerHTML=isPublic?"<i></i> Public":"<i></i> Private";showToast(isPublic?"Profile set to public":"Profile set to private","Prototype only — this privacy choice is not saved.")}});
document.querySelector(".menu-button").addEventListener("click",e=>{mobileNav.classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",mobileNav.classList.contains("open"))});
document.querySelector("#mentor-search").addEventListener("input",e=>{state.filters.search=e.target.value;renderDirectory()});document.querySelector("#sport-filter").addEventListener("change",e=>{state.filters.sport=e.target.value;renderDirectory()});document.querySelector("#focus-filter").addEventListener("change",e=>{state.filters.focus=e.target.value;renderDirectory()});document.querySelectorAll('input[name="format"]').forEach(i=>i.addEventListener("change",()=>{state.filters.formats=[...document.querySelectorAll('input[name="format"]:checked')].map(x=>x.value);renderDirectory()}));document.querySelector("#sort-filter").addEventListener("change",renderDirectory);document.querySelector("#clear-filters").addEventListener("click",clearFilters);document.querySelector("#empty-clear").addEventListener("click",clearFilters);
document.querySelector("#mentorship-request").addEventListener("submit",e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form),guardian=form.elements.guardianEmail;if(data.get("age")!=="18+"&&!guardian.value){guardian.setCustomValidity("Please add a guardian email for athletes under 18.");guardian.reportValidity();return}guardian.setCustomValidity("");state.requests.push({mentorId:data.get("mentorId"),goal:data.get("goal")});form.reset();closeModal(requestModal);renderRequests();showToast("Request added","It is visible in My requests until this page is refreshed.")});
document.querySelector("#mentor-application").addEventListener("submit",e=>{e.preventDefault();e.currentTarget.reset();showToast("Interest noted","Demo complete — nothing was stored or sent.")});document.querySelector("#report-form").addEventListener("submit",e=>{e.preventDefault();e.currentTarget.reset();closeModal(reportModal);showToast("Demo report complete","No report was sent because this prototype has no backend.")});document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelectorAll(".modal-backdrop.open").forEach(closeModal)});window.addEventListener("hashchange",()=>goToPage(location.hash.slice(1),false));
document.addEventListener("click",e=>{const control=e.target.closest("[data-carousel-target]");if(!control)return;const carousel=document.querySelector("#"+control.dataset.carouselTarget);if(!carousel)return;carousel.scrollBy({left:carousel.clientWidth*.88*Number(control.dataset.carouselDirection),behavior:"smooth"})});
renderMentors();renderRequests();renderGrowthChart("height");goToPage(location.hash.slice(1)||"home",false);
